mod cache;
mod config;
mod models;
mod services;

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use clap::Parser;

use config::AppConfig;
use models::format::Format;
use models::torrent::Torrent;
use models::torrentgroup::TorrentGroup;
use services::transcode;
use services::whatapi::WhatAPI;

#[derive(Parser)]
#[command(
    name = "orpheusmorebetter-rs",
    version,
    about = "Auto-transcoding tool for Orpheus.network"
)]
struct Cli {
    release_urls: Vec<String>,

    #[arg(short, long, help = "Only add one format per release")]
    single: bool,

    #[arg(
        short = 'j',
        long,
        default_value = "1",
        help = "Number of threads (currently only 1)"
    )]
    threads: usize,

    #[arg(long, default_value = "~/.orpheusmorebetter/config")]
    config: String,

    #[arg(long, default_value = "~/.orpheusmorebetter/cache")]
    cache: String,

    #[arg(short = 'U', long, help = "Don't upload new torrents")]
    no_upload: bool,

    #[arg(short = 'E', long, help = "Don't edit 24-bit torrents")]
    no_24bit_edit: bool,

    #[arg(
        short,
        long,
        help = "Mode: snatched, uploaded, both, seeding, all, none"
    )]
    mode: Option<String>,

    #[arg(short = 'S', long, help = "Mark URLs as already processed")]
    skip: bool,

    #[arg(short, long, help = "TOTP for 2FA")]
    totp: Option<String>,

    #[arg(short = 'o', long, help = "Source flag for created torrents")]
    source: Option<String>,

    #[arg(short, long, help = "Debug mode")]
    debug: bool,
}

fn banner() -> String {
    format!(
        "Torrent created with orpheusmorebetter version {}. Maintained by walkrflocka\n\
         This transcode was generated by an automated system",
        env!("CARGO_PKG_VERSION")
    )
}

fn create_description(torrent: &Torrent, flac_dir: &Path, format: &Format) -> Vec<String> {
    let resample = transcode::needs_resampling(flac_dir).unwrap_or(false);
    let rate = transcode::resample_rate(flac_dir).unwrap_or(None);
    let cmds = transcode::transcode_commands_desc(format, resample, rate);

    vec![
        format!("Transcode of [pl=noartist]{}[/pl]", torrent.id),
        String::new(),
        "Transcode process:".to_string(),
        String::new(),
        format!("[code]{}[/code]", cmds.join(" | ")),
        String::new(),
        banner(),
    ]
}

fn formats_needed(group: &TorrentGroup, torrent: &Torrent, requested: &[Format]) -> Vec<Format> {
    let allowed = torrent.allowed_transcodes();
    if allowed.is_empty() {
        return Vec::new();
    }

    let same_edition = |t: &Torrent| {
        t.media == torrent.media
            && t.remaster_year == torrent.remaster_year
            && t.remaster_title == torrent.remaster_title
            && t.remaster_record_label == torrent.remaster_record_label
            && t.remaster_catalogue_number == torrent.remaster_catalogue_number
    };

    let current: HashSet<(&str, &str)> = group
        .torrents
        .iter()
        .filter(|t| same_edition(t))
        .map(|t| (t.format.as_str(), t.encoding.as_str()))
        .collect();

    allowed
        .into_iter()
        .filter(|f| !current.contains(&(f.name, f.encoding)))
        .filter(|f| {
            requested
                .iter()
                .any(|r| r.name == f.name && r.encoding == f.encoding)
        })
        .collect()
}

fn html_unescape(s: &str) -> String {
    s.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .replace("&apos;", "'")
}

fn find_flac_dir(
    torrent: &Torrent,
    group: &TorrentGroup,
    data_dirs: &[PathBuf],
) -> Option<PathBuf> {
    if torrent.file_path.is_empty() {
        let file_from_list = html_unescape(&torrent.file_list)
            .split("{{{")
            .next()
            .unwrap_or("")
            .to_string();

        for d in data_dirs {
            let flac_file = d.join(&file_from_list);
            if !flac_file.exists() {
                continue;
            }

            let flac_dir = d.join(format!("{} ({}) [FLAC]", group.name, group.year));
            if !flac_dir.exists() {
                std::fs::create_dir_all(&flac_dir).ok()?;
            }
            std::fs::copy(&flac_file, flac_dir.join(flac_file.file_name().unwrap())).ok()?;
            return Some(flac_dir);
        }
        None
    } else {
        let unescaped = html_unescape(&torrent.file_path);
        for d in data_dirs {
            let candidate = d.join(&unescaped);
            if candidate.exists() {
                return Some(candidate);
            }
        }
        None
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> anyhow::Result<()> {
    let args = Cli::parse();

    if !std::path::Path::new("logs").exists() {
        std::fs::create_dir("logs")?;
    }

    let log_level = if args.debug {
        log::LevelFilter::Debug
    } else {
        log::LevelFilter::Info
    };

    env_logger::Builder::new()
        .filter_level(log_level)
        .format_timestamp_secs()
        .init();

    log::info!("Starting Up OrpheusMoreBetter...");

    let config = config::load_config(&args.config)?;
    let cache = cache::Cache::open(&args.cache)?;

    if args.skip {
        let skip_ids: Vec<u64> = args
            .release_urls
            .iter()
            .filter_map(|url| {
                url.split("torrentid=")
                    .nth(1)
                    .and_then(|s| s.split('&').next())
                    .and_then(|s| s.parse().ok())
            })
            .collect();
        cache.mark_all_seen(&skip_ids)?;
        log::info!("Marked {} torrents as skipped", skip_ids.len());
        return Ok(());
    }

    log::info!("Logging in to Orpheus Network...");
    let mut api = WhatAPI::new(&config, args.totp).await?;

    log::info!("Searching for transcode candidates...");

    let candidates: Vec<(u64, u64)> = if !args.release_urls.is_empty() {
        if args.release_urls.len() == 1 && Path::new(&args.release_urls[0]).is_file() {
            let content = std::fs::read_to_string(&args.release_urls[0])?;
            content
                .lines()
                .filter_map(|url| parse_candidate_url(url))
                .collect()
        } else {
            args.release_urls
                .iter()
                .filter_map(|url| parse_candidate_url(url))
                .collect()
        }
    } else {
        let mode = args.mode.as_deref().unwrap_or(&config.mode);
        if mode == "none" {
            log::info!("No urls provided and scraping is disabled");
            return Ok(());
        }
        let skip = cache.seen_set()?;
        api.get_candidates(mode, &skip, &config.media).await?
    };

    if candidates.is_empty() {
        log::info!("No candidates found, ending program.");
        return Ok(());
    }

    let upload_torrent = !args.no_upload;
    let source = args.source.as_deref().or(config.source.as_deref());

    for (group_id, torrent_id) in candidates {
        if let Err(e) = process_candidate(
            &mut api,
            &cache,
            &config,
            group_id,
            torrent_id,
            upload_torrent,
            source,
            args.single,
            args.no_24bit_edit,
            config.do_24_bit,
        )
        .await
        {
            log::error!("Error processing torrent {}: {}", torrent_id, e);
        }
    }

    log::info!("Process complete. Exiting.");
    Ok(())
}

async fn process_candidate(
    api: &mut WhatAPI,
    cache: &cache::Cache,
    config: &AppConfig,
    group_id: u64,
    torrent_id: u64,
    upload_torrent: bool,
    source: Option<&str>,
    single: bool,
    no_24bit_edit: bool,
    do_24_bit: u8,
) -> anyhow::Result<()> {
    let group = api.get_torrent_group(group_id).await?;

    let torrent = group
        .torrents
        .iter()
        .find(|t| t.id == torrent_id)
        .cloned()
        .ok_or_else(|| anyhow::anyhow!("Torrent {} not found in group {}", torrent_id, group_id))?;

    let release = format!("Release found: {} ({})", group.name, group.year);
    let release_url = format!("  Release URL: {}", api.release_url(&group, &torrent));
    log::info!("");
    log::info!("{}", release);
    log::info!("{}", release_url);

    let flac_dir = match find_flac_dir(&torrent, &group, &config.data_dirs) {
        Some(d) => d,
        None => {
            log::warn!("Flac dir not found for torrent {}", torrent_id);
            cache.mark_seen(torrent_id)?;
            return Ok(());
        }
    };

    let cleaned: String = flac_dir
        .to_string_lossy()
        .chars()
        .filter(|c| !c.is_control())
        .collect();
    if cleaned != flac_dir.to_string_lossy() {
        log::warn!("This OPH folder name has hidden characters.");
    }

    if do_24_bit > 0 {
        if let Ok(true) = transcode::is_24bit(&flac_dir) {
            if torrent.encoding != "24bit Lossless" {
                if no_24bit_edit {
                    log::warn!("Release is actually 24-bit lossless, skipping.");
                    cache.mark_seen(torrent_id)?;
                    return Ok(());
                }
                log::info!("  Marking release as 24bit lossless.");
                api.set_24bit(&torrent).await?;
            }
        }
    }

    if transcode::is_multichannel(&flac_dir).unwrap_or(false) {
        log::warn!("Multichannel release, unsupported - skipping");
        cache.mark_seen(torrent_id)?;
        return Ok(());
    }

    let needed = formats_needed(&group, &torrent, &config.formats);
    if needed.is_empty() {
        log::info!("  No formats needed.");
        cache.mark_seen(torrent_id)?;
        return Ok(());
    }

    log::info!(
        "  Formats needed: {}",
        needed
            .iter()
            .map(|f| format!("{} {}", f.name, f.encoding))
            .collect::<Vec<_>>()
            .join(", ")
    );

    let flac_files = transcode::find_files(&flac_dir, "flac")?;
    for flac_file in &flac_files {
        let (ok, msg) = services::tagging::check_tags(flac_file, false);
        if !ok {
            log::error!(
                "FLAC has unacceptable tags - skipping: {}",
                msg.unwrap_or_default()
            );
            cache.mark_seen(torrent_id)?;
            return Ok(());
        }
    }

    for format in &needed {
        if !flac_dir.exists() {
            log::error!("    Path not found - skipping: {}", flac_dir.display());
            break;
        }

        log::info!("    Creating format {}...", format.long_name);

        let tmpdir = tempfile::tempdir()?;

        let local_output_dir = config::output_dir_for_format(config, format);
        let local_torrent_dir = config::torrent_dir_for_format(config, format);
        std::fs::create_dir_all(&local_torrent_dir)?;

        match transcode::transcode_release(&flac_dir, &local_output_dir, format, &torrent, &group) {
            Ok(transcode_dir) => {
                let new_torrent = transcode::make_torrent(
                    &transcode_dir,
                    tmpdir.path(),
                    &config.tracker,
                    &api.passkey,
                    source,
                )?;

                log::info!("      Transcode successful, torrent created");

                if upload_torrent {
                    log::info!("      Uploading to OPS...");
                    let description = create_description(&torrent, &flac_dir, format);
                    api.upload(&group, &torrent, &new_torrent, format, &description)
                        .await?;
                }

                std::fs::copy(
                    &new_torrent,
                    local_torrent_dir.join(new_torrent.file_name().unwrap()),
                )?;
                log::info!("      Success.");

                if single {
                    break;
                }
            }
            Err(e) => {
                log::error!("      Error adding format {}: {}", format, e);
            }
        }
    }

    cache.mark_seen(torrent_id)?;
    Ok(())
}

fn parse_candidate_url(url: &str) -> Option<(u64, u64)> {
    let re = regex::Regex::new(r"id=(\d+).*?torrentid=(\d+)").ok()?;
    let caps = re.captures(url)?;
    let group_id: u64 = caps[1].parse().ok()?;
    let torrent_id: u64 = caps[2].parse().ok()?;
    Some((group_id, torrent_id))
}
